version: '3'
services:
  app:
    build: .
    ports:
      - "26079:26079"
    depends_on:
      - migrate
      - redis
      - postgres
    
  migrate:
    build: .
    command: python migrate.py
    depends_on:
      - postgres
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data