-- MySQL Script generated by MySQL Workbench
-- Sun Mar 29 00:31:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LibraryManagement
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LibraryManagement` ;

-- -----------------------------------------------------
-- Schema LibraryManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LibraryManagement` DEFAULT CHARACTER SET utf8 ;
USE `LibraryManagement` ;

-- -----------------------------------------------------
-- Table `LibraryManagement`.`authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryManagement`.`authors` ;

CREATE TABLE IF NOT EXISTS `LibraryManagement`.`authors` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryManagement`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryManagement`.`genres` ;

CREATE TABLE IF NOT EXISTS `LibraryManagement`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryManagement`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryManagement`.`books` ;

CREATE TABLE IF NOT EXISTS `LibraryManagement`.`books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `publication_year` INT NULL,
  `author_id` INT NULL,
  `genre_id` INT NULL,
  PRIMARY KEY (`book_id`),
  CONSTRAINT `author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `LibraryManagement`.`authors` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `genre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `LibraryManagement`.`genres` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `author_id_idx` ON `LibraryManagement`.`books` (`author_id` ASC) VISIBLE;

CREATE INDEX `genre_id_idx` ON `LibraryManagement`.`books` (`genre_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LibraryManagement`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryManagement`.`users` ;

CREATE TABLE IF NOT EXISTS `LibraryManagement`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LibraryManagement`.`borrowed_books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LibraryManagement`.`borrowed_books` ;

CREATE TABLE IF NOT EXISTS `LibraryManagement`.`borrowed_books` (
  `borrow_id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NULL,
  `user_id` INT NULL,
  `borrow_date` DATETIME NULL,
  `return_date` DATETIME NULL,
  PRIMARY KEY (`borrow_id`),
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `LibraryManagement`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `LibraryManagement`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `book_id_idx` ON `LibraryManagement`.`borrowed_books` (`book_id` ASC) VISIBLE;

CREATE INDEX `user_id_idx` ON `LibraryManagement`.`borrowed_books` (`user_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
